Contacts form section
Epaltechs/Setup-Portfolio pull request #3
Opened 2022-03-22 19:46 UTC by Epaltechs

In this part of my Portfolio Project, I:
- Add Contacts form in the footer
- Put Name field that accepts up to 30 characters
- Put an Email field that accepts only emails.
- Put a Message field that accepts up to 500 characters.
- Make sure all fields have placeholder text.
- Ensure that all fields have the correct type.
- Ensure that a user cannot submit the form if one or more of the fields is empty.
- Arrange that data be collected using the [Formspree service](https://formspree.io/html).

2022-03-22 20:20 UTC, prolajumokeoni requested changes
Hi @Epaltechs  and @RWUBAKWANAYO , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description



## Required Changes ♻️
_Check the comments under the review._
![almost-jumpin-gif](https://user-images.githubusercontent.com/69638013/159568448-8763d41c-8476-423b-a3af-cd7fb57ee3f9.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 20:20 UTC, prolajumokeoni commented on index.html
> +                    <h1 class="contact-title-1">Contact me</h1>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![sssa](https://user-images.githubusercontent.com/69638013/159566069-d8403d0e-1347-4858-becd-9ce31698e464.png)  | ![Screenshot_24](https://user-images.githubusercontent.com/69638013/159566045-20397890-a6f7-4ab7-beab-a19a3f03bca9.png)

- [ ] Kindly change this h1 tag to any hx tag from h2-h6, It is better for your page to have just one h1 tag for semantic purposes
- [ ] Kindly add the appropriate styling before the "contact me" header, there should be a spacing please check the Figma design

2022-03-22 20:20 UTC, prolajumokeoni commented on index.html
> +                   <hr/>
- [ ] Kindly delete this horizontal line as it is not required in your design 👍🏿

2022-03-22 20:20 UTC, prolajumokeoni commented on index.html
> +        <section id="contact-container">
- [ ] Kindly adjust the background image to look similar to the Figma design, you can adjust the [background size](https://www.w3schools.com/cssref/css3_pr_background-size.asp) of the image 💪🏿

2022-03-24 00:11 UTC, Epaltechs commented
In this commit, I:
- Change the tag in the contact form title from h1 to h5.
- Add margin to the "contact me" header.
- Delete the horizontal line.
- Adjust the background image size and position

2022-03-24 00:24 UTC, smunozmo approved these changes
Hi @Epaltechs, 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 06:51 UTC, merged